#!/bin/bash

#apps="3 19 18 20 6 5 8 59 227 29 10 94 11 23 2 7 53 13 31"
apps="19 18 20 6 5 8 59 227 29 10 94 11 23 2 7 53 13 31"

rm shadow*.data

for app in $apps; do
  ./compute -a $app \
            -p 0 \
            -v \
            -f data/app${app}
  mv shadowlru-size-curve.data shadowlru-size-curve-app${app}.data

  ./compute -a $app \
            -p 4 \
            -v \
            -f data/app${app}
  mv shadowslab-size-curve.data shadowslab-size-curve-app${app}-memcached.data

  ./compute -a $app \
            -p 4 \
            -M \
            -v \
            -f data/app${app}
  mv shadowslab-size-curve.data shadowslab-size-curve-app${app}-memcachier.data
done
