#!/bin/bash

# Runs the full mix (top 20 apps) of all of the apps together with the managed
# cache algorithm with the defaults.

source scripts/top-apps
apps="$top20"
source scripts/app-sizes

./lsm-sim \
  -a $app_lst \
  -p multislab \
  -M \
  -s $total_size \
  -S $((1024 * 1024)) \
  -f ./data/m.cap.out \
      2> err-top20-multislab.log \
      > top20-multislab.data

for private in 0 25 50 75 100; do
  ./lsm-sim \
    -a $app_lst \
    -p multi \
    -E normal \
    -N $private \
    -s $total_size \
    -S $((1024 * 1024)) \
    -f ./data/m.cap.out \
        2> err-top20-managed-$private-private.data \
        > top20-managed-$private-private.data
done

cat top20-managed-*.data > t
awk '/^time/ { if (head == 0) { print $0; head = 1; }; next; } { print $0; }' < t > top20-managed.data
rm t top20-managed-*.data
