#!/bin/bash

source scripts/top-apps
apps="$top3"
source scripts/app-sizes

for tax in 50; do
  ./lsm-sim \
    -a $app_lst \
    -p multi \
    -E normal \
    -s $total_size \
    -S $((1024 * 1024)) \
    -T $tax \
    -f ./data/m.cap.out \
        2> err-tax-multi-${tax}pct.log \
        > tax-multi-${tax}pct.data &
  pids="$pids $!"
  wait_too_many
done 

wait $pids

cat tax-*.data > t
awk < t '/^time/ { if (head == 0) { print $0; head = 1; }; next; } { print $0; }' > tax.data 
