#!/bin/bash

# Runs the full mix (top 20 apps) of all of the apps together with the managed
# cache algorithm with the defaults.

source scripts/top-apps
apps="$top20"
source scripts/app-sizes

echo ./lsm-sim \
  -a $app_lst \
  -p multi \
  -E normal \
  -N 75 \
  -s $total_size \
  -S $((1024 * 1024)) \
  -f ./data/m.cap.out \
      2> err-top20-managed.log \
      > top20-managed.data
