#!/bin/bash

#apps="3 19 18 20 6 5 8 59 227 29 10 94 11 23 2 7 53 13 31"
apps="19 18 20 6 8 59 227 29 10 94 11 23 2 7 53 13 31 5"
# ---------------------------------------------------| -> slow apps

factors="1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.75 1.8 1.9 2.0"

rm shadow*.data
rm shadow*.log

for factor in $factors; do
  echo Running $factor 
  ../lsm-sim -a 19 \
            -p 4 \
            -v \
            -f ../data/app19 \
            -g $factor 
  
  mv shadowslab-size-curve-app19-memcached.data shadowslab-size-curve-${factor}.data
  mv shadowslab-util-app19-memcached.data shadowslab-util-app19-${factor}.data

  a=$!

  wait $a
done
