#!/bin/bash

PASSWORD=$1

#apps="5 19 20"
apps="2 6 7 11 18 19 20"

declare -A cashflashlruk_app_size
cashflashlruk_app_size[2]=118577408
cashflashlruk_app_size[6]=7108608
cashflashlruk_app_size[7]=77842880
cashflashlruk_app_size[11]=7829952
cashflashlruk_app_size[19]=51209600
cashflashlruk_app_size[18]=6313216
cashflashlruk_app_size[20]=70953344

app_lst=$(echo $apps | sed "s/ /,/g")

finish() {
  $PASSWORD | sudo -S pkill lsm-sim
}
trap finish EXIT

pids=""
maxprocs=8

wait_too_many() {
  cnt=( $pids )
  cnt="${#cnt[@]}"
  if [[ "$cnt" == "$maxprocs" ]]; then
    wait $pids
    pids=""
  fi
}

for app in $apps; do

  dram_size=${cashflashlruk_app_size[$app]}
  dram_size=$(($dram_size/4))
  flash_size=$(($dram_size*7))
#flashcachelrukclk\
#    -D $dram_size \
#    -F $flash_size \
  ./lsm-sim \
    -a $app \
    -p flashcachelruk \
    -D $dram_size \
    -F $flash_size \
    -f ./data/app${app} \
        2> err-osdi-multislab-static-app$app.log &
  pids="$pids $!"
  wait_too_many
done 

wait $pids

